apiVersion: v1
kind: Service
metadata:
  name: menuscan-backend
  namespace: dev
  labels:
    app.kubernetes.io/name: menuscan-backend
    app.kubernetes.io/part-of: menuscan
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: menuscan-backend
  ports:
    - name: http
      port: 80
      targetPort: http
