"""Add name to DiningSession

Revision ID: 41766b8ca866
Revises: e8b5d3f07a24
Create Date: 2026-07-14 20:28:25.968471
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "41766b8ca866"
down_revision: str | None = "e8b5d3f07a24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dining_sessions", sa.Column("name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dining_sessions", "name")
    # ### end Alembic commands ###
