"""add calculation_type to bill_adjustments

Revision ID: b1fe7f837a7c
Revises: d7e9f3b1a8c4
Create Date: 2026-07-01 12:12:52.134746
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b1fe7f837a7c'
down_revision: str | None = 'd7e9f3b1a8c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_adjustments', sa.Column('calculation_type', sa.Enum('FIXED', 'PERCENTAGE', name='bill_adjustment_calculation_type'), server_default='FIXED', nullable=False))
    op.add_column('bill_adjustments', sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('bill_adjustments', sa.Column('calculated_amount', sa.Numeric(precision=14, scale=2), nullable=False))
    op.drop_column('bill_adjustments', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_adjustments', sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.drop_column('bill_adjustments', 'calculated_amount')
    op.drop_column('bill_adjustments', 'value')
    op.drop_column('bill_adjustments', 'calculation_type')
    # ### end Alembic commands ###
