"""update_target_language_constraint

Revision ID: ccfae21342e0
Revises: b4f2c1a9d8e7
Create Date: 2026-07-01 02:55:01.040897
"""

from collections.abc import Sequence

from alembic import op


revision: str = 'ccfae21342e0'
down_revision: str | None = 'b4f2c1a9d8e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_scan_sessions_target_language', 'scan_sessions', type_='check')
    op.create_check_constraint(
        'ck_scan_sessions_target_language',
        'scan_sessions',
        "target_language IN ('vi', 'en', 'zh', 'ja', 'ko', 'fr', 'th')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_scan_sessions_target_language', 'scan_sessions', type_='check')
    op.create_check_constraint(
        'ck_scan_sessions_target_language',
        'scan_sessions',
        "target_language IN ('vi', 'en')"
    )
    # ### end Alembic commands ###
